##
## EPITECH PROJECT, 2018
## arcade
## File description:
## created by Sid Djilali Saiah,
##

all:
	make -C SFML/
	make -C NCURSES/

clean:
	make clean -C SFML/
	make clean -C NCURSES/

fclean:
	make fclean -C SFML/
	make fclean -C NCURSES/

re: all

.PHONY: all clean fclean re