##
## EPITECH PROJECT, 2018
## arcade
## File description:
## created by Sid Djilali Saiah,
##

all:
	make -C NIBBLER/

clean:
	make clean -C NIBBLER/

fclean:
	make fclean -C NIBBLER/

re: all

.PHONY: all clean fclean re